\connect yam_pages

ALTER TABLE store ADD COLUMN pad_id VARCHAR(100), ADD COLUMN rev_id INT, ADD COLUMN timestamp TIMESTAMP WITH TIME ZONE, ADD COLUMN network_id VARCHAR(100);

SELECT * FROM store LIMIT 1;